export enum UserMessagePattern {
  CREATE = 'CREATE_USER',
  FIND_ALL = 'FIND_ALL_USER',
  FIND_ONE_BY_ID = 'FIND_ONE_USER_BY_ID',
  FIND_ONE_BY_EMAIL = 'FIND_ONE_USER_BY_EMAIL',
  VALIDATE = 'VALIDATE_USER',
  UPDATE = 'UPDATE_USER',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  DELETE = 'DELETE_USER',
}
